# Copyright (C) 2025 Alessandro Santini
# SPDX-License-Identifier: MIT

# Credits for the original implementations: Cecilio García Quirós

"""
Waveform
================================

IMRPhenomTHM interface class for waveform generation.
"""

from statistics import mode
from typing import Optional

import jax
jax.config.update("jax_enable_x64", True)
import jax.numpy as jnp
from interpax import CubicSpline
from jaxtyping import Array

from phentax.core import (
    AmplitudeCoeffs,
    PhaseCoeffs,
    compute_amplitude_coeffs_22,
    compute_amplitude_coeffs_hm,
    compute_phase_coeffs_22,
    compute_phase_coeffs_hm,
    imr_amplitude,
    imr_phase,
    imr_omega,
    imr_omega_dot,
    imr_amplitude_dot
)
from phentax.core.internals import WaveformParams, compute_waveform_params
from phentax.utils.coarse_graining import (
    generate_adaptive_grid,
    generate_uniform_grid,
    masked_evaluate,
)
from phentax.utils.config import setup_logging
from phentax.utils.utility import check_equal_bhs, mass_to_second, mode_to_lm,second_to_mass, mass_to_hz, df_dt_to_Hz_squared
from phentax.utils.ylm import (
    spin_weighted_spherical_harmonic,
    spin_weighted_spherical_harmonic_all_modes,
)

logger = setup_logging(__name__)

ALLOWED_POSITIVE_HMS = [21, 33, 44, 55]

import scipy
from functools import partial

class IMRPhenomTHM_TF:
    """
    Class for generating multi-polar, aligned-spin IMRPhenomTHM waveforms. 

    Generation using various flavours of the Fresnel time-frequency waveform generation method. 

    Parameters
    ----------
    higher_modes : Optional[Array | list | str], default "all"
        Higher modes to include beyond (2,2). Can be:
        - None: only (2,2) mode.
        - "all": include all allowed higher modes.
        - list or Array of integers: specific modes to include (e.g., [21, 33]). Only the positive m modes have to be specified.
    include_negative_modes : bool, default True
        Whether to include negative m modes by symmetry.
    coarse_grain : bool, default False
        Whether to use adaptive coarse-graining for time grid generation.
    use_splines : bool, default False
        Whether to use cubic spline interpolation for output waveforms.
    t_low_fit : bool, default True
        Whether to use the default fit for t_low in t(f).
    atol : float, default 1e-12
        Absolute tolerance for the t(f) root finding.
    rtol : float, default 1e-12
        Relative tolerance for the t(f) root finding.
    """

    def __init__(
        self,
        higher_modes: Optional[Array | list | str] = "all",
        include_negative_modes: bool = True,
        coarse_grain: bool = False,
        use_splines: bool = False,
        t_low_fit: bool = True,  # Use default fit for t_low if True.
        atol: float = 1e-12,
        rtol: float = 1e-12,
        # todo add time options. return interpolant / dense array / sparse array
    ):
        """
        Initialize the IMRPhenomTHM waveform generator.
        """

        if higher_modes is None:
            self.higher_modes = jnp.array([])
            self.has_hm = False
            logger.debug("No higher modes will be included.")

            self.ells: Array = jnp.array([2], dtype=jnp.int32)
            self.mms: Array = jnp.array([2], dtype=jnp.int32)

        else:
            if isinstance(higher_modes, str) and higher_modes == "all":
                self.higher_modes = jnp.asarray(ALLOWED_POSITIVE_HMS)

            elif isinstance(higher_modes, (list, Array)):
                self.higher_modes = jnp.asarray(higher_modes)
            else:
                raise TypeError(
                    "higher_modes must be None, a list, an array, or 'all'."
                )
            logger.debug("Including higher modes: %s", self.higher_modes)
            self.has_hm = True
            self.odd_modes_mask = (self.higher_modes % 2 == 1)[:, None]

            # extract ells and mms
            self.ells, self.mms = mode_to_lm(self.higher_modes)
            self.ells = jnp.concatenate([jnp.array([2]), self.ells])
            self.mms = jnp.concatenate([jnp.array([2]), self.mms])

        self.include_negative_modes = include_negative_modes

        if self.include_negative_modes:
            logger.debug("Negative m modes will be generated by symmetry.")
            # add negative modes to ells and mms
            self.negative_ls = self.ells[self.mms != 0]
            self.negative_mms = -self.mms[self.mms != 0]

        else:
            logger.debug("Negative m modes will NOT be included.")
            self.negative_ls = jnp.array([])
            self.negative_mms = jnp.array([])

        self.coarse_grain = coarse_grain
        logger.debug("Coarse graining set to %s", self.coarse_grain)

        self.use_splines = use_splines
        logger.debug("Using splines set to %s", self.use_splines)

        if t_low_fit:
            logger.debug("Using fit in t(f): t_low = - 0.015 * f^(-2.7)")
            self.t_low = 0.0  # will be set in get_time_of_frequency
        else:
            logger.debug("Using default t_low = -1e9 M in t(f).")
            self.t_low = -1e9

        self.atol = atol
        self.rtol = rtol

    @jax.jit(static_argnames="self")
    def _compute_coeffs_22(
        self,
        wf_params: WaveformParams,
    ) -> tuple[WaveformParams, AmplitudeCoeffs, PhaseCoeffs]:
        """
        Compute amplitude and phase coefficients for the (2,2) mode.
        This updates relevant derived parameters in wf_params, and sets the time array if not provided.

        Parameters
        ----------
        wf_params : WaveformParams
            Waveform parameters of the binary.
        Returns
        -------
        wf_params : WaveformParams
            Updated derived parameters.
        amplitude_coeffs : AmplitudeCoeffs
            Amplitude coefficients for the (2,2) mode.
        phase_coeffs : PhaseCoeffs
            Phase coefficients for the (2,2) mode.
        """
        wf_params, phase_coeffs = compute_phase_coeffs_22(wf_params)
        amplitude_coeffs = compute_amplitude_coeffs_22(wf_params, phase_coeffs)

        return wf_params, amplitude_coeffs, phase_coeffs

    @jax.jit(static_argnames="self")
    def _compute_amp_phase_22(
        self,
        times: Array,
        mask: Array,
        wf_params: WaveformParams,
        amplitude_coeffs: AmplitudeCoeffs,
        phase_coeffs: PhaseCoeffs,
    ) -> tuple[Array, Array]:
        """
        Compute amplitude and phase for the (2,2) mode.

        Parameters
        ----------
        times : Array
            Time array.
        mask : Array
            Boolean mask indicating valid time points.
        wf_params : WaveformParams
            Waveform parameters of the binary.
        amplitude_coeffs : AmplitudeCoeffs
            Amplitude coefficients for the (2,2) mode.
        phase_coeffs : PhaseCoeffs
            Phase coefficients for the (2,2) mode.

        Returns
        -------
        amplitude_22 : Array
            Amplitude array for the (2,2) mode.
        phase_22 : Array
            Phase array for the (2,2) mode.
        """

        amplitude_22 = jnp.abs(
            masked_evaluate(
                times,
                mask,
                lambda t: imr_amplitude(
                    t,
                    wf_params.eta,
                    amplitude_coeffs,
                    phase_coeffs,
                ),
            )
        )

        phase_22 = masked_evaluate(
            times,
            mask,
            lambda t: imr_phase(
                t,
                wf_params.eta,
                phase_coeffs,
            )
            - phase_coeffs.phoff
            - phase_coeffs.phiref0,
            fill_value=0.0,
        )

        return amplitude_22[None, :], phase_22[None, :]
    
    @jax.jit(static_argnames="self")
    def _compute_phase_coeffs_hm(
        self,
        mode: int | Array,
        wf_params: WaveformParams,
        phase_coeffs_22: PhaseCoeffs,
    ) -> tuple[Array]:
        """
        Utility function to compute phase coefficients for a given higher mode (beyond 22).
        """
        
        # m = mode % 10
        amplitude_coeffs = compute_amplitude_coeffs_hm(wf_params, phase_coeffs_22, mode)
        phase_coeffs = compute_phase_coeffs_hm(
                wf_params,
                phase_coeffs_22,
                OmegaCutPNAMP=amplitude_coeffs.omegaCutPNAMP,
                PhiCutPNAMP=amplitude_coeffs.phiCutPNAMP,
                mode=mode,
            )
            
        return(phase_coeffs,amplitude_coeffs)

    @jax.jit(static_argnames="self")
    def _compute_amp_phase_hm(
        self,
        mode: int | Array,
        times: Array,
        mask: Array,
        wf_params: WaveformParams,
        phase_coeffs_22: PhaseCoeffs,
        phase_22: Array,
    ) -> tuple[Array, Array]:
        """
        Compute amplitude and phase for a given higher mode (beyond 22).
        It sets odd-m modes to zero if equal mass/spin.

        Parameters
        ----------
        mode : int | Array
            The (l,m) mode to compute, encoded as lm (e.g., 21 for (2,1)).
        times : Array
            Time array.
        mask : Array
            Boolean mask indicating valid time points.
        wf_params : WaveformParams
            Waveform parameters of the binary.
        phase_coeffs_22 : PhaseCoeffs
            Phase coefficients for the (2,2) mode.
        phase_22 : Array
            Phase array for the (2,2) mode.

        Returns
        -------
        amplitude_hm : Array
            Amplitude array for the higher mode.
        phase_hm : Array
            Phase array for the higher mode.
        """

        m = mode % 10
        amplitude_coeffs = compute_amplitude_coeffs_hm(wf_params, phase_coeffs_22, mode)
        phase_coeffs = compute_phase_coeffs_hm(
            wf_params,
            phase_coeffs_22,
            OmegaCutPNAMP=amplitude_coeffs.omegaCutPNAMP,
            PhiCutPNAMP=amplitude_coeffs.phiCutPNAMP,
            mode=mode,
        )

        amplitude_hm = masked_evaluate(
            times,
            mask,
            lambda t: imr_amplitude(
                t,
                wf_params.eta,
                amplitude_coeffs,
                phase_coeffs_22,
            ),
        )

        def compute_scalar_phase(_t, _mask, _p22):
            return jax.lax.cond(
                _mask,
                lambda _: imr_phase(
                    _t,
                    wf_params.eta,
                    phase_coeffs,
                    phase_22=_p22,
                )
                - phase_coeffs.phoff
                - phase_coeffs.phiref0 * m / 2.0,
                lambda _: 0.0,
                operand=None,
            )

        phase_hm = jax.vmap(compute_scalar_phase)(
            times, mask, phase_22 + phase_coeffs_22.phoff + phase_coeffs_22.phiref0
        )  # avoid double counting phoff and phiref0 in the 22 mode

        return amplitude_hm, phase_hm

    def _compute_all_modes(
        self,
        times: Array,
        mask: Array,
        wf_params: WaveformParams,
        amplitude_coeffs_22: AmplitudeCoeffs,
        phase_coeffs_22: PhaseCoeffs,
    ) -> tuple[Array, Array]:
        """
        Compute amplitude and phase for all modes: (2,2) and higher modes.

        Parameters
        ----------
        times : Array
            Time array.
        mask : Array
            Boolean mask indicating valid time points.
        wf_params : WaveformParams
            Waveform parameters of the binary.
        amplitude_coeffs_22 : AmplitudeCoeffs
            Amplitude coefficients for the (2,2) mode.
        phase_coeffs_22 : PhaseCoeffs
            Phase coefficients for the (2,2) mode.

        Returns
        -------
        all_amplitudes : Array
            Amplitude arrays for all modes, shape (Nmodes, Ntimes).
        all_phases : Array
            Phase arrays for all modes, shape (Nmodes, Ntimes).
        """

        amplitude_22, phase_22 = self._compute_amp_phase_22(
            times, mask, wf_params, amplitude_coeffs_22, phase_coeffs_22
        )

        if not self.has_hm:
            return amplitude_22, phase_22

        amplitude_hms, phase_hms = jax.vmap(
            lambda mode: self._compute_amp_phase_hm(
                mode, times, mask, wf_params, phase_coeffs_22, phase_22[0]
            )
        )(self.higher_modes)

        equal_black_holes = check_equal_bhs(
            wf_params.m1, wf_params.m2, wf_params.chi1, wf_params.chi2
        )

        should_zero = self.odd_modes_mask & equal_black_holes

        # Apply the mask using jnp.where
        amplitude_hms = jnp.where(should_zero, 0.0, amplitude_hms)
        phase_hms = jnp.where(should_zero, 0.0, phase_hms)

        # now stack 22 with hms
        all_amplitudes = jnp.concatenate(
            [amplitude_22, amplitude_hms], axis=0
        )  # shape (Nmodes, Ntimes)
        all_phases = jnp.concatenate(
            [phase_22, phase_hms], axis=0
        )  # shape (Nmodes, Ntimes)

        return all_amplitudes, all_phases
    

    

    @jax.jit(static_argnames="self")
    def combine_amp_phase(self, amplitudes: Array, phases: Array) -> Array:
        """
        Combine amplitude and phase into complex strain :math:`h = A * e^{-i \\phi}`.

        Parameters
        ----------
        amplitudes : Array
            Amplitude arrays for all modes, shape (Nmodes, Ntimes).
        phases : Array
            Phase arrays for all modes, shape (Nmodes, Ntimes).
        Returns
        -------
        h_modes : Array
            Complex strain arrays for all modes, shape (Nmodes, Ntimes).
        """
        h_modes = amplitudes * jnp.exp(-1j * phases)
        return h_modes

    def compute_hlms(
        self,
        m1: float | Array,
        m2: float | Array,
        chi1z: float | Array,
        chi2z: float | Array,
        distance: float | Array,
        phi_ref: float | Array,
        f_ref: float | Array,
        f_min: float | Array,
        inclination: float,
        psi: float | Array,
        delta_t: float = 15.0,
        t_min: float = jnp.nan,
        t_ref: float = jnp.nan,
    ) -> tuple[Array, Array, Array]:
        """
        Generate complex strain :math:`h_{lm}` for all modes for a single input binary.

        Parameters
        ----------
        m1 : float | Array
            Mass of the first black hole in solar masses.
        m2 : float | Array
            Mass of the second black hole in solar masses.
        chi1z : float | Array
            Dimensionless spin of the first black hole along the orbital angular momentum.
        chi2z : float | Array
            Dimensionless spin of the second black hole along the orbital angular momentum.
        distance : float | Array
            Luminosity distance to the binary in megaparsecs.
        phi_ref : float | Array
            Reference phase at frequency f_ref in radians.
        f_ref : float | Array
            Reference frequency in Hz.
        f_min : float | Array
            Minimum frequency in Hz.
        inclination : float
            Inclination angle of the binary in radians.
        psi : float | Array
            Polarization angle in radians.
        delta_t : float, default 15.0
            Time step for waveform generation in seconds.
        t_min : float, default jnp.nan
            Minimum time for waveform generation in seconds. If NaN, will be set by the minimum frequency.
        t_ref : float, default jnp.nan
            Reference time for waveform generation in seconds. If NaN, will be set by the reference frequency.

        Returns
        -------
        times : Array
            Time array in seconds.
        mask : Array
            Boolean mask indicating valid time points.
        h_lms : Array
            Complex strain arrays for all modes, shape (Nbinaries, Nmodes, Ntimes).
        """

        wf_params, times, mask, amplitude_coeffs_22, phase_coeffs_22 = (
            self.initial_processing(
                m1,
                m2,
                chi1z,
                chi2z,
                distance,
                phi_ref,
                f_ref,
                f_min,
                inclination,
                psi,
                delta_t,
                t_min,
                t_ref,
            )
        )
        amplitudes, phases = jax.vmap(self._compute_all_modes)(
            times,
            mask,
            wf_params,
            amplitude_coeffs_22,
            phase_coeffs_22,
        )  # shape (Nbinaries, Nmodes, Ntimes)

        h_lms = (
            self.combine_amp_phase(amplitudes, phases) * wf_params.amp_factor
        )  # [:, None, None]

        # compute negative m modes by symmetry
        if self.include_negative_modes:
            h_lmms = (-1) ** self.negative_ls[None, :, None] * jnp.conj(h_lms)
            h_lms = jnp.concatenate([h_lms, h_lmms], axis=1)

        times = mass_to_second(times, wf_params.total_mass)

        return times, mask, h_lms

    def compute_polarizations(
        self,
        m1: float | Array,
        m2: float | Array,
        chi1z: float | Array,
        chi2z: float | Array,
        distance: float | Array,
        phi_ref: float | Array,
        f_ref: float | Array,
        f_min: float | Array,
        inclination: float,
        psi: float | Array,
        delta_t: float = 15.0,
        t_min: float = jnp.nan,
        t_ref: float = jnp.nan,
    ) -> tuple[Array, Array, Array, Array]:
        """
        Generate plus and cross polarizations from the computed modes.

        Parameters
        ----------
        m1 : float | Array
            Mass of the first black hole in solar masses.
        m2 : float | Array
            Mass of the second black hole in solar masses.
        chi1z : float | Array
            Dimensionless spin of the first black hole along the orbital angular momentum.
        chi2z : float | Array
            Dimensionless spin of the second black hole along the orbital angular momentum.
        distance : float | Array
            Luminosity distance to the binary in megaparsecs.
        phi_ref : float | Array
            Reference phase at frequency f_ref in radians.
        f_ref : float | Array
            Reference frequency in Hz.
        f_min : float | Array
            Minimum frequency in Hz.
        inclination : float
            Inclination angle of the binary in radians.
        psi : float | Array
            Polarization angle in radians.
        delta_t : float, default 15.0
            Time step for waveform generation in seconds.
        t_min : float, default jnp.nan
            Minimum time for waveform generation in seconds. If NaN, will be set by the minimum frequency.
        t_ref : float, default jnp.nan
            Reference time for waveform generation in seconds. If NaN, will be set by the reference frequency.
        times : Optional[Array], default None
            Output time array in seconds. If provided and `self.use_splines = True`, the output polarizations will be interpolated onto this time array.
            Otherwise, the internal time arrays will be used.

        Returns
        -------
        times : Array
            Time array in seconds. If `self.use_splines = True` and `times` is provided, this will be the provided time array.
            If `self.use_splines = True` and `times` is None, this will be the internal time array used for waveform generation.
            If `self.use_splines = False`, this will be the internal time array used for waveform generation.
        mask : Array
            Boolean mask indicating valid time points. To be used only if `self.use_splines = False`.
        h_plus : Array | CubicSpline
            Plus polarization strain. If `self.use_splines = True` and `times` is `None`, this will be a CubicSpline object representing the interpolated strain.
            If `self.use_splines = True` and `times` is provided, this will be the interpolated strain evaluated at the provided times.
            If `self.use_splines = False`, this will be the strain evaluated at the internal time array.
        h_cross : Array | CubicSpline
            Cross polarization strain. If `self.use_splines = True` and `times` is `None`, this will be a CubicSpline object representing the interpolated strain.
            If `self.use_splines = True` and `times` is provided, this will be the interpolated strain evaluated at the provided times.
            If `self.use_splines = False`, this will be the strain evaluated at the internal time array.
        """
        times, mask, h_lms = self.compute_hlms(
            m1,
            m2,
            chi1z,
            chi2z,
            distance,
            phi_ref,
            f_ref,
            f_min,
            inclination,
            psi,
            delta_t,
            t_min,
            t_ref,
        )

        y_lms = spin_weighted_spherical_harmonic_all_modes(
            jnp.atleast_1d(inclination)[:, None],
            jnp.pi / 2.0 - jnp.atleast_1d(phi_ref)[:, None],
            self.ells,
            self.mms,
        )
        if self.include_negative_modes:
            y_lmms = spin_weighted_spherical_harmonic_all_modes(
                jnp.atleast_1d(inclination)[:, None],
                jnp.pi / 2.0 - jnp.atleast_1d(phi_ref)[:, None],
                self.negative_ls,
                self.negative_mms,
            )
            y_lms = jnp.concatenate([y_lms, y_lmms], axis=1)

        # breakpoint()
        strain = jnp.sum(h_lms * y_lms, axis=1)
        h_plus = jnp.real(strain)
        h_cross = -jnp.imag(strain)

        h_plus, h_cross = self.rotate_by_polarization_angle(h_plus, h_cross, psi)

        return times, mask, h_plus, h_cross

    # Define the single-binary computation to be vmapped
    @jax.jit(static_argnames="self")
    def _compute_strain_single(
        self,
        _times,
        _mask,
        _wf_params,
        _amp_coeffs_22,
        _phase_coeffs_22,
        _inc,
        _phi_ref,
    ):
        # 1. Compute (2,2) mode
        amp22, phase22 = self._compute_amp_phase_22(
            _times, _mask, _wf_params, _amp_coeffs_22, _phase_coeffs_22
        )
        # Remove singleton dim (1, Ntimes) -> (Ntimes,)
        amp22 = amp22[0]
        phase22 = phase22[0]

        h22 = amp22 * jnp.exp(-1j * phase22) * _wf_params.amp_factor

        # Project (2,2)
        # spin_weighted_spherical_harmonic takes (theta, phi, l, m)
        # phi for Ylm is usually pi/2 - phi_ref
        y22 = spin_weighted_spherical_harmonic(_inc, jnp.pi / 2.0 - _phi_ref, 2, 2)
        strain = h22 * y22

        if self.include_negative_modes:
            # Add (2,-2)
            # h(2,-2) = (-1)^2 * conj(h(2,2)) = conj(h22)
            y2m2 = spin_weighted_spherical_harmonic(
                _inc, jnp.pi / 2.0 - _phi_ref, 2, -2
            )
            strain += jnp.conj(h22) * y2m2

        if not self.has_hm:
            return strain

        # 2. Loop over higher modes
        n_modes = self.higher_modes.shape[0]

        # Pre-compute equal BH check for this binary
        equal_bhs = check_equal_bhs(
            _wf_params.m1, _wf_params.m2, _wf_params.chi1, _wf_params.chi2
        )

        def body_fun(i, current_strain):
            mode = self.higher_modes[i]

            # Compute HM waveform
            amp_hm, phase_hm = self._compute_amp_phase_hm(
                mode, _times, _mask, _wf_params, _phase_coeffs_22, phase22
            )

            # Apply odd-m masking for equal BHs
            m_mode = mode % 10
            is_odd = (m_mode % 2) == 1
            should_zero = is_odd & equal_bhs

            amp_hm = jnp.where(should_zero, 0.0, amp_hm)
            phase_hm = jnp.where(should_zero, 0.0, phase_hm)

            h_hm = amp_hm * jnp.exp(-1j * phase_hm) * _wf_params.amp_factor

            # Project (l, m)
            l_mode = mode // 10
            y_lm = spin_weighted_spherical_harmonic(
                _inc, jnp.pi / 2.0 - _phi_ref, l_mode, m_mode
            )
            term = h_hm * y_lm

            if self.include_negative_modes:
                # Add (l, -m)
                # h(l,-m) = (-1)^l * conj(h(l,m))
                y_lmm = spin_weighted_spherical_harmonic(
                    _inc, jnp.pi / 2.0 - _phi_ref, l_mode, -m_mode
                )
                # (-1)^l is 1.0 if l even, -1.0 if l odd
                parity = jnp.where(l_mode % 2 == 0, 1.0, -1.0)
                term += parity * jnp.conj(h_hm) * y_lmm

            return current_strain + term

        strain = jax.lax.fori_loop(0, n_modes, body_fun, strain)
        return strain

    def compute_polarizations_at_once(
        self,
        m1: float | Array,
        m2: float | Array,
        chi1z: float | Array,
        chi2z: float | Array,
        distance: float | Array,
        phi_ref: float | Array,
        f_ref: float | Array,
        f_min: float | Array,
        inclination: float,
        psi: float | Array,
        delta_t: float = 15.0,
        t_min: float = jnp.nan,
        t_ref: float = jnp.nan,
    ) -> tuple[Array, Array, Array, Array]:
        """
        Generate plus and cross polarizations, but computing the :math:`h_{lm}` individually for each mode to save memory.

        Parameters
        ----------
        m1 : float | Array
            Mass of the first black hole in solar masses.
        m2 : float | Array
            Mass of the second black hole in solar masses.
        chi1z : float | Array
            Dimensionless spin of the first black hole along the orbital angular momentum.
        chi2z : float | Array
            Dimensionless spin of the second black hole along the orbital angular momentum.
        distance : float | Array
            Luminosity distance to the binary in megaparsecs.
        phi_ref : float | Array
            Reference phase at frequency f_ref in radians.
        f_ref : float | Array
            Reference frequency in Hz.
        f_min : float | Array
            Minimum frequency in Hz.
        inclination : float
            Inclination angle of the binary in radians.
        psi : float | Array
            Polarization angle in radians.
        delta_t : float, default 15.0
            Time step for waveform generation in seconds.
        t_min : float, default jnp.nan
            Minimum time for waveform generation in seconds. If NaN, will be set by the minimum frequency.
        t_ref : float, default jnp.nan
            Reference time for waveform generation in seconds. If NaN, will be set by the reference frequency.
        times : Optional[Array], default None
            Output time array in seconds. If provided and `self.use_splines = True`, the output polarizations will be interpolated onto this time array.

        Returns
        -------
        times_out : Array
            Time array in seconds.
        mask_out : Array
            Boolean mask indicating valid time points.
        h_plus_out : Array
            Plus polarization strain.
        h_cross_out : Array
            Cross polarization strain.
        """
        wf_params, times, mask, amplitude_coeffs_22, phase_coeffs_22 = (
            self.initial_processing(
                m1,
                m2,
                chi1z,
                chi2z,
                distance,
                phi_ref,
                f_ref,
                f_min,
                inclination,
                psi,
                delta_t,
                t_min,
                t_ref,
            )
        )

        strain = jnp.zeros_like(times, dtype=jnp.complex128)

        # Vmap over the batch of parameters
        strain = jax.vmap(self._compute_strain_single)(
            times,
            mask,
            wf_params,
            amplitude_coeffs_22,
            phase_coeffs_22,
            wf_params.inclination,
            wf_params.phi_ref,
        )

        # Compute polarizations
        h_plus = jnp.real(strain)
        h_cross = -jnp.imag(strain)

        # Rotate by polarization angle psi
        h_plus, h_cross = self.rotate_by_polarization_angle(
            h_plus, h_cross, wf_params.psi
        )

        # Convert times to seconds
        times_sec = mass_to_second(times, wf_params.total_mass)

        return times_sec, mask, h_plus, h_cross

    def spline_polarizations(
        self,
        times: Array,
        h_plus: Array,
        h_cross: Array,
    ) -> tuple[Array, Array]:
        """
        Interpolate plus and cross polarizations onto a given time array using cubic splines.

        Parameters
        ----------
        times : Array
            Time array in seconds to interpolate onto.
        h_plus : Array
            Plus polarization strain.
        h_cross : Array
            Cross polarization strain.

        Returns
        -------
        h_plus_interp : Array
            Interpolated plus polarization strain.
        h_cross_interp : Array
            Interpolated cross polarization strain.
        """
        h_plus_splines = jax.vmap(lambda t, hp: CubicSpline(t, hp))(times, h_plus)
        h_cross_splines = jax.vmap(lambda t, hc: CubicSpline(t, hc))(times, h_cross)

        if times is None:
            return h_plus_splines, h_cross_splines

        h_plus_interp = jax.vmap(lambda spl: spl(times))(h_plus_splines)
        h_cross_interp = jax.vmap(lambda spl: spl(times))(h_cross_splines)

        return h_plus_interp, h_cross_interp

    @jax.jit(static_argnames="self")
    def rotate_by_polarization_angle(
        self,
        h_plus: Array,
        h_cross: Array,
        psi: float | Array,
    ) -> tuple[Array, Array]:
        """
        Rotate the plus and cross polarizations by the polarization angle :math:`\\psi`.

        Parameters
        ----------
        h_plus : Array
            Plus polarization strain.
        h_cross : Array
            Cross polarization strain.
        psi : float | Array
            Polarization angle in radians.

        Returns
        -------
        h_plus_rotated : Array
            Rotated plus polarization strain.
        h_cross_rotated : Array
            Rotated cross polarization strain.
        """
        cos_2psi = jnp.cos(2.0 * psi)
        sin_2psi = jnp.sin(2.0 * psi)

        h_plus_rotated = h_plus * cos_2psi - h_cross * sin_2psi
        h_cross_rotated = h_plus * sin_2psi + h_cross * cos_2psi

        return h_plus_rotated, h_cross_rotated

    @jax.jit(static_argnames="self")
    def _process_parameters(
        self,
        m1: float | Array,
        m2: float | Array,
        chi1z: float | Array,
        chi2z: float | Array,
        distance: float | Array,
        phi_ref: float | Array,
        f_ref: float | Array,
        f_min: float | Array,
        inclination: float | Array,
        psi: float | Array,
        delta_t: float | Array = 15.0,
        t_min: float | Array = jnp.nan,
        t_ref: float | Array = jnp.nan,
    ) -> WaveformParams:
        """
        Process input parameters and compute derived parameters.
        Convert all source parameters to arrays to enable batching.

        Parameters
        ----------
        m1 : float | Array
            Mass of the first black hole in solar masses.
        m2 : float | Array
            Mass of the second black hole in solar masses.
        chi1z : float | Array
            Dimensionless spin of the first black hole along the orbital angular momentum.
        chi2z : float | Array
            Dimensionless spin of the second black hole along the orbital angular momentum.
        distance : float | Array
            Luminosity distance to the binary in megaparsecs.
        phi_ref : float | Array
            Reference phase at frequency f_ref in radians.
        f_ref : float | Array
            Reference frequency in Hz.
        f_min : float | Array
            Minimum frequency in Hz.
        inclination : float | Array
            Inclination angle of the binary in radians.
        psi : float | Array
            Polarization angle in radians.
        delta_t : float | Array, default 5.0
            Time step for waveform generation in seconds.
        t_min : float | Array, default jnp.nan
            Minimum time for waveform generation in seconds. If NaN, will be set by the minimum frequency.
        t_ref : float | Array, default jnp.nan
            Reference time for waveform generation in seconds. If NaN, will be set by the reference frequency.

        Returns
        -------
        wf_params : WaveformParams
            Waveform parameters of the binary, including derived parameters like total mass, symmetric mass ratio,
            and time arrays.
        """

        wf_params = compute_waveform_params(
            m1=jnp.atleast_1d(m1),
            m2=jnp.atleast_1d(m2),
            s1z=jnp.atleast_1d(chi1z),
            s2z=jnp.atleast_1d(chi2z),
            distance=jnp.atleast_1d(distance),
            inclination=jnp.atleast_1d(inclination),
            phi_ref=jnp.atleast_1d(phi_ref),
            psi=jnp.atleast_1d(psi),
            f_ref=f_ref,
            f_min=f_min,
            delta_t=delta_t,
            t_min=t_min,
            t_ref=t_ref,
            t_low=self.t_low,
            atol=self.atol,
            rtol=self.rtol,
        )

        return wf_params

    def get_time_grids(
        self,
        wf_params: WaveformParams,
    ) -> tuple[Array, Array]:
        """
        Generate the time grid for waveform generation based on waveform parameters.

        Parameters
        ----------
        wf_params : WaveformParams
            Waveform parameters of the binary.

        Returns
        -------
        times : Array
            Time array in units of mass for waveform generation.
        mask : Array
            Boolean mask indicating valid time points.
        """
        max_steps = int(jnp.max(jnp.atleast_1d(wf_params.length)))

        if self.coarse_grain:
            times, mask = generate_adaptive_grid(
                wf_params.eta,
                wf_params.Mt_min,
                wf_params.Mt_end,
                max_steps=max_steps // 2,  # allocate half steps for adaptive grid
            )

        else:
            times, mask = generate_uniform_grid(
                wf_params.Mt_min,
                wf_params.Mt_end,
                wf_params.Mdelta_t,
                max_steps=max_steps,
            )

        return times, mask


    def initial_processing_TF(
        self,
        m1: float | Array,
        m2: float | Array,
        chi1z: float | Array,
        chi2z: float | Array,
        distance: float | Array,
        phi_ref: float | Array,
        f_ref: float | Array,
        f_min: float | Array,
        inclination: float | Array,
        psi: float | Array,
        delta_t: float | Array = 15.0,
        t_min: float | Array = jnp.nan,
        t_ref: float | Array = jnp.nan,
    ) -> tuple[WaveformParams, Array, Array, AmplitudeCoeffs, PhaseCoeffs]:
        """
        Initial processing to compute waveform parameters.

        Note explicitly not computing over times here, as TF waveforms may use different time grids. We just want the:
            - Transformed waveform parameters
            - Amplitude and phase coeffs for 22 mode

        Parameters
        ----------
        Parameters
        ----------
        m1 : float | Array
            Mass of the first black hole in solar masses.
        m2 : float | Array
            Mass of the second black hole in solar masses.
        chi1z : float | Array
            Dimensionless spin of the first black hole along the orbital angular momentum.
        chi2z : float | Array
            Dimensionless spin of the second black hole along the orbital angular momentum.
        distance : float | Array
            Luminosity distance to the binary in megaparsecs.
        phi_ref : float | Array
            Reference phase at frequency f_ref in radians.
        f_ref : float | Array
            Reference frequency in Hz.
        f_min : float | Array
            Minimum frequency in Hz.
        inclination : float | Array
            Inclination angle of the binary in radians.
        psi : float | Array
            Polarization angle in radians.
        delta_t : float | Array, default 5.0
            Time step for waveform generation in seconds.
        t_min : float | Array, default jnp.nan
            Minimum time for waveform generation in seconds. If NaN, will be set by the minimum frequency.
        t_ref : float | Array, default jnp.nan
            Reference time for waveform generation in seconds. If NaN, will be set by the reference frequency.

        Returns
        -------
        wf_params : WaveformParams
            Waveform parameters of the binary, including derived parameters like total mass, symmetric mass ratio,
            and time arrays.
        times : Array
            Time array in units of mass for waveform generation.
        mask : Array
            Boolean mask indicating valid time points.
        amplitude_coeffs_22 : AmplitudeCoeffs
            Amplitude coefficients for the (2,2) mode.
        phase_coeffs_22 : PhaseCoeffs
            Phase coefficients for the (2,2) mode.
        """

        wf_params = self._process_parameters(
            m1,
            m2,
            chi1z,
            chi2z,
            distance,
            phi_ref,
            f_ref,
            f_min,
            inclination,
            psi,
            delta_t,
            t_min,
            t_ref,
        )
        wf_params, amplitude_coeffs_22, phase_coeffs_22 = jax.vmap(
            self._compute_coeffs_22
        )(wf_params)


        return wf_params, amplitude_coeffs_22, phase_coeffs_22

    @jax.jit(static_argnums=[0,16])
    def get_tf_fresnel_waveform_vanilla_TF(self,
                                time_grid: Array,
                                frequency_grid: Array,
                                m1: float | Array,
                                m2: float | Array,
                                chi1z: float | Array,
                                chi2z: float | Array,
                                distance: float | Array,
                                phi_ref: float | Array,
                                f_ref: float | Array,
                                f_min: float | Array,
                                inclination: float | Array,
                                psi: float | Array,
                                delta_t: float = 15.0,
                                t_min: float = jnp.nan,
                                t_ref: float = jnp.nan,
                                closest_f_bins: int = 10,
                                time_of_projections : float | Array = 0.0,
                            ) -> tuple[Array, Array, Array, Array]: # Check dimensionality of this when done. 

        """
        Implementation of time-frequency Fresnel waveform generation.

        Everything aligning at merger. 
        """

        num_sources = jnp.atleast_1d(m1).shape[0]

        # print("Number of sources: ", num_sources)
        # Ignore times for now 
        wf_params, amplitude_coeffs_22, phase_coeffs_22 = (
                    self.initial_processing_TF(
                        m1,
                        m2,
                        chi1z,
                        chi2z,
                        distance,
                        phi_ref,
                        f_ref,
                        f_min,
                        inclination,
                        psi,
                        delta_t,
                        t_min,
                        t_ref,
                    )
                )
        # This is the minimum time for every waveform in the batch in mass units 
        min_time_M_units = wf_params.Mt_min 
        # print('min time M units:',min_time_M_units)

        #Convert every single min time to physical units (seconds) to see what is the longest waveform in absolute (real) time
        time_min_physical_all = mass_to_second(min_time_M_units, wf_params.total_mass)

        # print('All time min physical (s):',time_min_physical_all)

        # Pad to smallest min time (real units) to ensure all waveforms fit in the time grid
        min_time_s_units = jnp.min(time_min_physical_all)
        # print('Padded min time (real units):',min_time_s_units)

        # Check the length of the longest signal is not longer than the grid: 
        # assert jnp.abs(min_time_s_units) > jnp.abs(time_grid[-1]), "Time grid is not long enough to contain the longest waveform!"
        # print('Time min physical (s):',min_time_s_units)

        # print('Original time grid:',time_grid)

        # shift time grid to be negative, limited by the length of the longest waveform. (Physical units, seconds)
        time_grid += min_time_s_units
        # print('Shifted time grid (should be negative):',time_grid)
    

        # Work out what OUR time grid corresponds to in mass units for each binary 
        time_grids_mass_units = jax.vmap(second_to_mass, in_axes=(None, 0))(time_grid, wf_params.total_mass)

        new_mask = jnp.ones_like(time_grid, dtype=bool)


        # print('Time grid in mass units:',time_grids_mass_units,time_grids_mass_units.shape)

        # Compute amplitudes and phases for every binary over the time grid and mask    
        # Note: new_mask is the same for all sources, so we use in_axes=None for it (which are in seconds intiially and mapped uniquely to mass units for each binary)
        amplitudes, phases = jax.vmap(self._compute_all_modes, in_axes = (0, None, 0, 0, 0))(
            time_grids_mass_units,
            new_mask,
            wf_params,
            amplitude_coeffs_22,
            phase_coeffs_22,
        )  
        # Amplitudes and phases shape: [num_sources, num_modes, num_times]
        n_modes = amplitudes.shape[1]
        # print('Amplitudes shape:',amplitudes.shape)
        # print('Phases shape:',phases.shape)
       
       # Get higher order modes phase coeffs
        phase_hm_coeffs,_ = jax.vmap(
            lambda wp, pc22: jax.vmap(
                lambda mode: self._compute_phase_coeffs_hm(mode, wp, pc22)
            )(self.higher_modes)
        )(wf_params, phase_coeffs_22)

        # print('Phase HM coeffs:',phase_hm_coeffs)

        # Combine 22 and HM phase coeffs 
        overall_phase_coeffs = jax.tree_util.tree_map(
            lambda p22, phm: jnp.concatenate([p22[:, None], phm], axis=1),
            phase_coeffs_22,
            phase_hm_coeffs,
        )
        # print('Phase overall coeffs:',overall_phase_coeffs)

        # amplitudes shape: [num_sources, num_modes, num_times]
        # amp_factor shape: [num_sources] -> need to reshape for broadcasting
        amplitudes *= wf_params.amp_factor[:, None, None]

        # # For each source find the time at which to begin the waveform. (Is this handled inside the waveform parameter computation? i have no idea)
        # t_min_index = jnp.nonzero(jnp.abs(amplitudes[:,0,:]),axis=1)

        # Back to sensible and positive time grid
        time_grid -= min_time_s_units
        
        # Frequency grid spacing (assumed uniform)
        dF = frequency_grid[1] - frequency_grid[0]

        # Waveform storage container, will be combined into TF later
        waveform_storage = jnp.zeros((time_grid.size,num_sources,n_modes,2*closest_f_bins), dtype=jnp.complex128)

        # Storage for frequency indices at each time step (# 2*closest_f_bins because we are storing bins on either side of the closest frequency for each harmonic for each time)
        frequency_indices_storage = jnp.zeros((time_grid.size,num_sources,n_modes,2*closest_f_bins), dtype=jnp.int32)

        #tf grid 
        # tf_grid = jnp.zeros((num_sources,time_grid.size, frequency_grid.size), dtype=jnp.complex128)

        # In principle can also be vmapped over time steps here, however I think it would be completely unreadable and a nightmare to debug/maintain.. 
        for time_index in range(time_grid.size - 1):  # -1 to avoid index out of bounds with t_1
                
                t_0 = time_grid[time_index]
                t_1 = time_grid[time_index+1]

                # Convert t_0 to mass units for each binary for each binary
                # (TODO: can be taken out of the loop, can be an array operation as we know the time-grid apriori so can be vmapped across that )
                t_0_mass = jax.vmap(second_to_mass, in_axes=(None, 0))(t_0 + min_time_s_units, wf_params.total_mass) # nSources, 

                Amps = amplitudes[:,:, time_index] # Source, #Mode , # Time 
                Phases = phases[:,:, time_index]   # Source, #Mode , # Time 

                # Lets see if we can vmap across modes here to speed things up a bit ... I may regret this. So we are vmapping across both sources and modes now. For each time 

                
                # overall_phase_coeffs contains phase coeffs for all modes at once for all binaries (Only positive modes remember)
                # Using this compute f_0 and f_dot for each source and each mode at this time
                # 
                # Shapes:
                #   t_0_mass: (num_sources,)
                #   wf_params.eta: (num_sources,)
                #   overall_phase_coeffs: dictionary like structure but each field has shape (num_sources, num_modes, ...)
                #
                # Nested vmap explanation:
                # -------------------------
                # We need to compute imr_omega for every (source, mode) combination.
                # 
                # OUTER vmap (over sources):
                #   - Iterates over axis 0 of t_0_mass, eta, and overall_phase_coeffs
                #   - For source i: t_0_mass[i] is scalar, eta[i] is scalar, 
                #     overall_phase_coeffs[i] is a pytree with shape (num_modes, ...) per field
                #
                # INNER vmap (over modes for a single source):
                #   - For a single source, iterates over axis 0 of phase_coeffs (the modes axis)
                #   - Computes imr_omega(t, eta, p) for each mode's phase coeffs p
                #   - t and eta are fixed scalars from the outer vmap
                #
                # Result: f_0 has shape (num_sources, num_modes) (same with f_dot)
                
                # pc is the phase coefficents for a single source, shape (num_modes, ...), p is the phase coeffs for a single mode, shape (...)
                f_0 = jax.vmap(
                    lambda t, eta, pc: jax.vmap(lambda p: imr_omega(t, eta, p))(pc)
                )(t_0_mass, wf_params.eta, overall_phase_coeffs) / (2 * jnp.pi)  # IN MASS UNITS
                # print('F0 (mass units) shape:', f_0.shape)

                f_dot = jax.vmap(
                    lambda t, eta, pc: jax.vmap(lambda p: imr_omega_dot(t, eta, p))(pc)
                )(t_0_mass, wf_params.eta, overall_phase_coeffs) / (2 * jnp.pi)  # IN MASS UNITS
                # print('F dot (mass units) shape:', f_dot.shape)

                # Convert f_0 and f_dot to Hz and Hz^2 respectively
                f_0 = jax.vmap(mass_to_hz, in_axes=(0, 0))(f_0, wf_params.total_mass)
                f_dot = jax.vmap(df_dt_to_Hz_squared, in_axes=(0, 0))(f_dot, wf_params.total_mass)
                # print('F0 (Hz) shape:', f_0.shape) 
                # print('F dot (Hz^2) shape:', f_dot.shape)

                # NOTE: the potential for frequencies around f0 going out of bounds is dealt with later. 

                # Compute closest frequency indexes in the grid for each source and mode
                # Uniform grid → direct arithmetic instead of materializing an (nSrc, nMode, nFreq) tensor
                closest_frequency_indexes = jnp.round((f_0 - frequency_grid[0]) / dF).astype(jnp.int32)
                closest_frequency_indexes = jnp.clip(closest_frequency_indexes, 0, frequency_grid.size - 1)
                closest_frequencies = frequency_grid[closest_frequency_indexes]
                # Closest frequency shape is (num_sources, num_modes) and closest frequency indexes is also (num_sources, num_modes). 
                # Same shape as f_0 and f_dot

                # print('Closest frequency indexes shape:', closest_frequency_indexes.shape,closest_frequency_indexes.flatten().shape)

                # for every frequency in closest_frequencies, generate a frequency array around it +/- closest_f_bins by going in steps of dF
                frequencies = jax.vmap(
                    lambda center_freqs: jnp.arange(
                        0,
                        2*closest_f_bins,
                    ) * dF + center_freqs - closest_f_bins*dF, # Starting from center_freqs - closest_f_bins*dF to center_freqs + closest_f_bins*dF
                )(closest_frequencies.flatten()).reshape(num_sources,n_modes,2*closest_f_bins)  #
                # shape of frequencies is (num_sources, num_modes, 2*closest_f_bins) 

                # Holds indices for each frequency in frequencies, which will be used to place the waveform values in the correct position in the final tf grid.
                frequency_indices = jax.vmap(
                    lambda indices: jnp.arange(
                        0,
                        2*closest_f_bins,
                    )+ indices - closest_f_bins, # Starting from indices - closest_f_bins to indices + closest_f_bins
                )(closest_frequency_indexes.flatten()).reshape(num_sources,n_modes,2*closest_f_bins)

                # print('Frequencies shape:', frequencies.shape)
                # print('Frequencies:', frequencies)
                # print('Frequency indices shape:', frequency_indices.shape)
                # print('Frequency indices:', frequency_indices)
                
                # The newaxis here is accounting for the frequency dimension, 
                #     remember we generated a single A, f, f_dot for each source and mode,
                #      but now we have an array of frequencies for each source and mode, so we need to add a new axis to Amps,
                #      Phases, f_0 and f_dot to allow for broadcasting when computing the waveform values for each frequency.
                h_prefactor = Amps[:,:,jnp.newaxis]*jnp.exp(1j*Phases[:,:,jnp.newaxis])/jnp.sqrt(2*f_dot[:,:,jnp.newaxis]) * jnp.exp(-1j*jnp.pi*((f_0[:,:,jnp.newaxis] - frequencies)**2)/f_dot[:,:,jnp.newaxis])

                # Fresnel integral stuff (all )
                v_nm_end = v(f_dot,t_0,t_1,frequencies,f_0)
                v_nm_begin = v(f_dot,t_0,t_0,frequencies,f_0)
                S_vn_end, C_vn_end = jax.scipy.special.fresnel(v_nm_end)
                S_vn_begin, C_vn_begin = jax.scipy.special.fresnel(v_nm_begin)

                I = C_vn_end - C_vn_begin + 1j*(S_vn_end - S_vn_begin)
                waveform = h_prefactor * I
                
                # Store each waveform in its own 'tf grid' for now. 
                # NOTE: Final implementation will use something much closer to the direct likelihood/inner product computation. Maybe....
                # NOTE: In its current form this is *NOT* the actual TF grid, the frequency axis has not yet been placed in the correct position,
                #         we are just storing the waveforms for each time step and each mode in a temporary array here, 
                waveform_storage = waveform_storage.at[time_index,:,:,:].set(waveform)

                # Store the corresponding frequency indices for each waveform value, which will be used to place the values in the correct position in the final tf grid.
                frequency_indices_storage = frequency_indices_storage.at[time_index,:,:,:].set(frequency_indices)

        # Note in theory one can do the direct likelihood/inner product computation directly from waveform storage I think. 


        # TEMPORARY/DEV
        # Transpose to (num_sources, num_times, num_modes, 2*closest_f_bins) for vmapping (basically changing around order of axes)
        waveform_storage_transposed = waveform_storage.transpose(1, 0, 2, 3)
        frequency_indices_transposed = frequency_indices_storage.transpose(1, 0, 2, 3)

        # Number of frequency bins in the full grid
        n_freq = frequency_grid.size # TODO: can be precomputed before this function. 

        # Generate spherical harmonics for all modes and sources at once.
        y_lms = spin_weighted_spherical_harmonic_all_modes(
                    jnp.atleast_1d(inclination)[:, None],
                    jnp.pi / 2.0 - jnp.atleast_1d(phi_ref)[:, None],
                    self.ells,
                    self.mms,
                ) #Shape (num_sources, num_modes,1)
        
        y_lmms = spin_weighted_spherical_harmonic_all_modes(
            jnp.atleast_1d(inclination)[:, None],
            jnp.pi / 2.0 - jnp.atleast_1d(phi_ref)[:, None],
            self.negative_ls,
            self.negative_mms, 
            ) #Shape (num_sources, num_modes,1)
        
        K_plus_lms = 1/2*(y_lms[:,:,0] + (-1)**self.negative_ls*y_lmms[:,:,0].conj()).conj() # Overall Conj to flip the fourier convention (Compared to that of Marsat appendix. )
        K_cross_lms = 1j/2*(y_lms[:,:,0] - (-1)**self.negative_ls*y_lmms[:,:,0].conj()).conj()
        # Shapes of K are (num_sources, num_modes) where num_modes includes only the positive modes (we are doing the reflection trick for negative modes for non-precessing binaries)
        

        # total_fresnel_waveforms_h_plus = jnp.einsum('ni,ijk->jk',K_plus_lms,tf_grid)
        # total_fresnel_waveforms_h_cross = jnp.einsum('ni,ijk->jk',K_cross_lms,tf_grid)

        # h_plus_rotated, h_cross_rotated = imr.rotate_by_polarization_angle(total_fresnel_waveforms_h_plus, total_fresnel_waveforms_h_cross, psi)


        def place_waveform_at_time(waveform_modes, indices_modes,K_plus, K_cross):
            """
            Place waveforms from all modes into the frequency grid for a single time step.
            
            waveform_modes: (n_modes, 2*closest_f_bins) - complex waveform values
            indices_modes: (n_modes, 2*closest_f_bins) - frequency bin indices
            K_plus: (n_modes,) - complex coefficients for plus polarization
            K_cross: (n_modes,) - complex coefficients for cross polarization
            
            Returns: (n_freq,) - summed waveform across modes at correct frequency positions
            """
            # Multiply K coefficients *before* flattening so each mode's scalar
            # broadcasts across its 2*closest_f_bins frequency entries.
            # K_plus/K_cross: (n_modes,), waveform_modes: (n_modes, 2*closest_f_bins) 
            h_plus_modes = K_plus[:, None] * waveform_modes   # (n_modes, 2*closest_f_bins)
            h_cross_modes = K_cross[:, None] * waveform_modes

            # Now flatten across modes and frequency bins
            flat_h_plus = h_plus_modes.flatten()
            flat_h_cross = h_cross_modes.flatten()
            flat_indices = indices_modes.flatten()

            # Mask out-of-bounds indices: zero their contributions
            valid_mask = (flat_indices >= 0) & (flat_indices < n_freq)
            flat_h_plus = jnp.where(valid_mask, flat_h_plus, 0.0)
            flat_h_cross = jnp.where(valid_mask, flat_h_cross, 0.0)
            
            # Clip indices to valid range so .at[].add() doesn't error with out-of-bounds indices.
            # The zeroed values mean nothing is actually added for these entries.
            flat_indices = jnp.clip(flat_indices, 0, n_freq - 1)

            result_plus = jnp.zeros(n_freq, dtype=jnp.complex128).at[flat_indices].add(flat_h_plus)
            result_cross = jnp.zeros(n_freq, dtype=jnp.complex128).at[flat_indices].add(flat_h_cross)

            return result_plus, result_cross

        def process_source(waveforms_per_source, indices_per_source,K_plus, K_cross):
            """
            Process all time steps for a single source.
            
            waveforms_per_source: (n_times, n_modes, 2*closest_f_bins), this is a version of the TF grid for one source (with the wrong frequency axis)
            indices_per_source: (n_times, n_modes, 2*closest_f_bins)
            K_plus: (n_modes,) - complex coefficients for plus polarization
            K_cross: (n_modes,) - complex coefficients for cross polarization
            
            Returns: (n_times, n_freq) - TF map for this source
            """
            # This is vmapping across timesteps
            return jax.vmap(place_waveform_at_time, in_axes = (0, 0, None, None) )(waveforms_per_source, indices_per_source,K_plus, K_cross)

        # NOTE: this is a 2 nested vmap, its just done like this right now for readability and debugging. 
        # Vmap over sources to get final tf_grid with shape (num_sources, num_times, num_freq)
        tf_grid_plus, tf_grid_cross = jax.vmap(process_source)(
            waveform_storage_transposed,
            frequency_indices_transposed,
            K_plus_lms,
            K_cross_lms
        ) # vmap over *SOURCES*

        # Rotate by polarization angle psi for each source (applied to all modes in the same way)
        tf_grid_plus, tf_grid_cross = jax.vmap(self.rotate_by_polarization_angle)(
            tf_grid_plus, tf_grid_cross, wf_params.psi
        )
        
        
        return(tf_grid_plus, tf_grid_cross) #Each (time_grid, frequency_grid, tf_grid) # Returning the full TF grid for all sources.


    @jax.jit(static_argnums=[0,16])
    def get_tf_fresnel_waveform_TF_amp_variation(self,
                                time_grid: Array,
                                frequency_grid: Array,
                                m1: float | Array,
                                m2: float | Array,
                                chi1z: float | Array,
                                chi2z: float | Array,
                                distance: float | Array,
                                phi_ref: float | Array,
                                f_ref: float | Array,
                                f_min: float | Array,
                                inclination: float | Array,
                                psi: float | Array,
                                delta_t: float = 15.0,
                                t_min: float = jnp.nan,
                                t_ref: float = jnp.nan,
                                closest_f_bins: int = 10,
                                time_of_projections : float | Array = 0.0,
                            ) -> tuple[Array, Array, Array, Array]: # Check dimensionality of this when done. 

        """
        Implementation of time-frequency Fresnel waveform generation.

        Everything aligning at merger. 
        """

        num_sources = jnp.atleast_1d(m1).shape[0]

        # print("Number of sources: ", num_sources)
        # Ignore times for now 
        wf_params, amplitude_coeffs_22, phase_coeffs_22 = (
                    self.initial_processing_TF(
                        m1,
                        m2,
                        chi1z,
                        chi2z,
                        distance,
                        phi_ref,
                        f_ref,
                        f_min,
                        inclination,
                        psi,
                        delta_t,
                        t_min,
                        t_ref,
                    )
                )
        # This is the minimum time for every waveform in the batch in mass units 
        min_time_M_units = wf_params.Mt_min 
        # print('min time M units:',min_time_M_units)

        #Convert every single min time to physical units (seconds) to see what is the longest waveform in absolute (real) time
        time_min_physical_all = mass_to_second(min_time_M_units, wf_params.total_mass)

        # print('All time min physical (s):',time_min_physical_all)

        # Pad to smallest min time (real units) to ensure all waveforms fit in the time grid
        min_time_s_units = jnp.min(time_min_physical_all)
        # print('Padded min time (real units):',min_time_s_units)

        # Check the length of the longest signal is not longer than the grid: 
        # assert jnp.abs(min_time_s_units) > jnp.abs(time_grid[-1]), "Time grid is not long enough to contain the longest waveform!"
        # print('Time min physical (s):',min_time_s_units)

        # print('Original time grid:',time_grid)

        # shift time grid to be negative, limited by the length of the longest waveform. (Physical units, seconds)
        time_grid += min_time_s_units
        # print('Shifted time grid (should be negative):',time_grid)
    

        # Work out what OUR time grid corresponds to in mass units for each binary 
        time_grids_mass_units = jax.vmap(second_to_mass, in_axes=(None, 0))(time_grid, wf_params.total_mass)

        new_mask = jnp.ones_like(time_grid, dtype=bool)


        # print('Time grid in mass units:',time_grids_mass_units,time_grids_mass_units.shape)

        # Compute amplitudes and phases for every binary over the time grid and mask    
        # Note: new_mask is the same for all sources, so we use in_axes=None for it (which are in seconds intiially and mapped uniquely to mass units for each binary)
        amplitudes, phases = jax.vmap(self._compute_all_modes, in_axes = (0, None, 0, 0, 0))(
            time_grids_mass_units,
            new_mask,
            wf_params,
            amplitude_coeffs_22,
            phase_coeffs_22,
        )  
        # Amplitudes and phases shape: [num_sources, num_modes, num_times]
        n_modes = amplitudes.shape[1]
        # print('Amplitudes shape:',amplitudes.shape)
        # print('Phases shape:',phases.shape)
       
       # Get higher order modes phase coeffs
        phase_hm_coeffs, amplitude_hm_coeffs = jax.vmap(
            lambda wp, pc22: jax.vmap(
                lambda mode: self._compute_phase_coeffs_hm(mode, wp, pc22)
            )(self.higher_modes)
        )(wf_params, phase_coeffs_22)

        # print('Phase HM coeffs:',phase_hm_coeffs)

        # Combine 22 and HM phase coeffs 
        overall_phase_coeffs = jax.tree_util.tree_map(
            lambda p22, phm: jnp.concatenate([p22[:, None], phm], axis=1),
            phase_coeffs_22,
            phase_hm_coeffs,
        )

        overall_amplitude_coeffs = jax.tree_util.tree_map(
            lambda a22, ahm: jnp.concatenate([a22[:, None], ahm], axis=1),
            amplitude_coeffs_22,
            amplitude_hm_coeffs,
        )

        # print('Phase overall coeffs:',overall_phase_coeffs)

        # amplitudes shape: [num_sources, num_modes, num_times]
        # amp_factor shape: [num_sources] -> need to reshape for broadcasting
        amplitudes *= wf_params.amp_factor[:, None, None]

        # # For each source find the time at which to begin the waveform. (Is this handled inside the waveform parameter computation? i have no idea)
        # t_min_index = jnp.nonzero(jnp.abs(amplitudes[:,0,:]),axis=1)

        # Back to sensible and positive time grid
        time_grid -= min_time_s_units
        
        # Frequency grid spacing (assumed uniform)
        dF = frequency_grid[1] - frequency_grid[0]

        # Waveform storage container, will be combined into TF later
        waveform_storage = jnp.zeros((time_grid.size,num_sources,n_modes,2*closest_f_bins), dtype=jnp.complex128)

        # Storage for frequency indices at each time step (# 2*closest_f_bins because we are storing bins on either side of the closest frequency for each harmonic for each time)
        frequency_indices_storage = jnp.zeros((time_grid.size,num_sources,n_modes,2*closest_f_bins), dtype=jnp.int32)

        #tf grid 
        # tf_grid = jnp.zeros((num_sources,time_grid.size, frequency_grid.size), dtype=jnp.complex128)

        # In principle can also be vmapped over time steps here, however I think it would be completely unreadable and a nightmare to debug/maintain.. 
        for time_index in range(time_grid.size - 1):  # -1 to avoid index out of bounds with t_1
                
                t_0 = time_grid[time_index]
                t_1 = time_grid[time_index+1]

                # Convert t_0 to mass units for each binary for each binary
                # (TODO: can be taken out of the loop, can be an array operation as we know the time-grid apriori so can be vmapped across that )
                t_0_mass = jax.vmap(second_to_mass, in_axes=(None, 0))(t_0 + min_time_s_units, wf_params.total_mass) # nSources, 

                Amps = amplitudes[:,:, time_index] # Source, #Mode , # Time 
                Phases = phases[:,:, time_index]   # Source, #Mode , # Time 
                # Lets see if we can vmap across modes here to speed things up a bit ... I may regret this. So we are vmapping across both sources and modes now. For each time 

                
                # overall_phase_coeffs contains phase coeffs for all modes at once for all binaries (Only positive modes remember)
                # Using this compute f_0 and f_dot for each source and each mode at this time
                # 
                # Shapes:
                #   t_0_mass: (num_sources,)
                #   wf_params.eta: (num_sources,)
                #   overall_phase_coeffs: dictionary like structure but each field has shape (num_sources, num_modes, ...)
                #
                # Nested vmap explanation:
                # -------------------------
                # We need to compute imr_omega for every (source, mode) combination.
                # 
                # OUTER vmap (over sources):
                #   - Iterates over axis 0 of t_0_mass, eta, and overall_phase_coeffs
                #   - For source i: t_0_mass[i] is scalar, eta[i] is scalar, 
                #     overall_phase_coeffs[i] is a pytree with shape (num_modes, ...) per field
                #
                # INNER vmap (over modes for a single source):
                #   - For a single source, iterates over axis 0 of phase_coeffs (the modes axis)
                #   - Computes imr_omega(t, eta, p) for each mode's phase coeffs p
                #   - t and eta are fixed scalars from the outer vmap
                #
                # Result: f_0 has shape (num_sources, num_modes) (same with f_dot)
                
                # pc is the phase coefficents for a single source, shape (num_modes, ...), p is the phase coeffs for a single mode, shape (...)
                f_0 = jax.vmap(
                    lambda t, eta, pc: jax.vmap(lambda p: imr_omega(t, eta, p))(pc)
                )(t_0_mass, wf_params.eta, overall_phase_coeffs) / (2 * jnp.pi)  # IN MASS UNITS
                # print('F0 (mass units) shape:', f_0.shape)

                f_dot = jax.vmap(
                    lambda t, eta, pc: jax.vmap(lambda p: imr_omega_dot(t, eta, p))(pc)
                )(t_0_mass, wf_params.eta, overall_phase_coeffs) / (2 * jnp.pi)  # IN MASS UNITS
                # print('F dot (mass units) shape:', f_dot.shape)

                # Convert f_0 and f_dot to Hz and Hz^2 respectively
                f_0 = jax.vmap(mass_to_hz, in_axes=(0, 0))(f_0, wf_params.total_mass)
                f_dot = jax.vmap(df_dt_to_Hz_squared, in_axes=(0, 0))(f_dot, wf_params.total_mass)
                # print('F0 (Hz) shape:', f_0.shape) 
                # print('F dot (Hz^2) shape:', f_dot.shape)

                A_dot_0 = jax.vmap(
                    lambda t, eta, a_coeffs, p_coeffs, amp_factor: jax.vmap(lambda a: imr_amplitude_dot(t, eta, a, p_coeffs))(a_coeffs) * amp_factor    
                )(t_0_mass, wf_params.eta, overall_amplitude_coeffs, phase_coeffs_22, wf_params.amp_factor) #* wf_params.amp_factor[:, None] # Shape (num_sources, num_modes) # amp_factor has shapr (num_sources,) so we add a new axis for modes to allow for broadcasting.
                
                # NOTE since t is in mass units this is still in mass units for the time so we need to convert back to seconds!
                
                # Note we use mass_to_hz here as its basically 1/M, which is the transformation we want since dA/dt_{s} = dA/dt_{M} * dt_{M}/dt_{s} and dt_{M}/dt_{s} is basically 1/M (up to factors of G and c which we set to 1).
                A_dot_0 = jax.vmap(mass_to_hz, in_axes=(0, 0))(A_dot_0, wf_params.total_mass) # Convert A_dot_0 to physical units (seconds) for each source and mode. Still shape (num_sources, num_modes)  
                
                # print('A_dot_0 shape:', A_dot_0.shape)
                # print('A_dot_0:', A_dot_0)

                # NOTE: the potential for frequencies around f0 going out of bounds is dealt with later. 

                # Compute closest frequency indexes in the grid for each source and mode
                # Uniform grid → direct arithmetic instead of materializing an (nSrc, nMode, nFreq) tensor
                closest_frequency_indexes = jnp.round((f_0 - frequency_grid[0]) / dF).astype(jnp.int32)
                closest_frequency_indexes = jnp.clip(closest_frequency_indexes, 0, frequency_grid.size - 1)
                closest_frequencies = frequency_grid[closest_frequency_indexes] 
                # Closest frequency shape is (num_sources, num_modes) and closest frequency indexes is also (num_sources, num_modes). 
                # Same shape as f_0 and f_dot

                # print('Closest frequency indexes shape:', closest_frequency_indexes.shape,closest_frequency_indexes.flatten().shape)

                # for every frequency in closest_frequencies, generate a frequency array around it +/- closest_f_bins by going in steps of dF
                frequencies = jax.vmap(
                    lambda center_freqs: jnp.arange(
                        0,
                        2*closest_f_bins,
                    ) * dF + center_freqs - closest_f_bins*dF, # Starting from center_freqs - closest_f_bins*dF to center_freqs + closest_f_bins*dF
                )(closest_frequencies.flatten()).reshape(num_sources,n_modes,2*closest_f_bins)  #
                # shape of frequencies is (num_sources, num_modes, 2*closest_f_bins) 

                # Holds indices for each frequency in frequencies, which will be used to place the waveform values in the correct position in the final tf grid.
                frequency_indices = jax.vmap(
                    lambda indices: jnp.arange(
                        0,
                        2*closest_f_bins,
                    )+ indices - closest_f_bins, # Starting from indices - closest_f_bins to indices + closest_f_bins
                )(closest_frequency_indexes.flatten()).reshape(num_sources,n_modes,2*closest_f_bins)

                # print('Frequencies shape:', frequencies.shape)
                # print('Frequencies:', frequencies)
                # print('Frequency indices shape:', frequency_indices.shape)
                # print('Frequency indices:', frequency_indices)
                
                # Fresnel integral stuff (all )
                v_nm_end = v(f_dot,t_0,t_1,frequencies,f_0)
                v_nm_begin = v(f_dot,t_0,t_0,frequencies,f_0)
                S_vn_end, C_vn_end = jax.scipy.special.fresnel(v_nm_end)
                S_vn_begin, C_vn_begin = jax.scipy.special.fresnel(v_nm_begin)

                I = C_vn_end - C_vn_begin + 1j*(S_vn_end - S_vn_begin)

                # Adot components 
                delta_s = jnp.sin(jnp.pi/2*v_nm_end**2)- jnp.sin(jnp.pi/2*v_nm_begin**2)
                delta_c = jnp.cos(jnp.pi/2*v_nm_end**2)- jnp.cos(jnp.pi/2*v_nm_begin**2)

                I_prime = delta_s - 1j * delta_c

                
                waveform = jnp.exp(1j*Phases[:,:,jnp.newaxis])*jnp.exp(-1j*jnp.pi*((f_0[:,:,jnp.newaxis] - frequencies)**2)/f_dot[:,:,jnp.newaxis])*(
                    Amps[:,:,jnp.newaxis]/jnp.sqrt(2*f_dot[:,:,jnp.newaxis]) * I + # Basic fresnel contribution 
                    A_dot_0[:,:,jnp.newaxis]/(2*jnp.pi*f_dot[:,:,jnp.newaxis]) * I_prime - # Contribution from amplitude variation (A_dot term)
                    A_dot_0[:,:,jnp.newaxis]*(f_0[:,:,jnp.newaxis]-frequencies)/(jnp.sqrt(2)*(f_dot[:,:,jnp.newaxis])**(3/2))* I # Contribution from amplitude variation (f_0 dot term)
                )
                waveform_storage = waveform_storage.at[time_index,:,:,:].set(waveform)

                # Store the corresponding frequency indices for each waveform value, which will be used to place the values in the correct position in the final tf grid.
                frequency_indices_storage = frequency_indices_storage.at[time_index,:,:,:].set(frequency_indices)

        # Note in theory one can do the direct likelihood/inner product computation directly from waveform storage I think. 


        # TEMPORARY/DEV
        # Transpose to (num_sources, num_times, num_modes, 2*closest_f_bins) for vmapping (basically changing around order of axes)
        waveform_storage_transposed = waveform_storage.transpose(1, 0, 2, 3)
        frequency_indices_transposed = frequency_indices_storage.transpose(1, 0, 2, 3)

        # Number of frequency bins in the full grid
        n_freq = frequency_grid.size # TODO: can be precomputed before this function. 

        # Generate spherical harmonics for all modes and sources at once.
        y_lms = spin_weighted_spherical_harmonic_all_modes(
                    jnp.atleast_1d(inclination)[:, None],
                    jnp.pi / 2.0 - jnp.atleast_1d(phi_ref)[:, None],
                    self.ells,
                    self.mms,
                ) #Shape (num_sources, num_modes,1)
        
        y_lmms = spin_weighted_spherical_harmonic_all_modes(
            jnp.atleast_1d(inclination)[:, None],
            jnp.pi / 2.0 - jnp.atleast_1d(phi_ref)[:, None],
            self.negative_ls,
            self.negative_mms, 
            ) #Shape (num_sources, num_modes,1)
        
        K_plus_lms = 1/2*(y_lms[:,:,0] + (-1)**self.negative_ls*y_lmms[:,:,0].conj()).conj() # Overall Conj to flip the fourier convention (Compared to that of Marsat appendix. )
        K_cross_lms = 1j/2*(y_lms[:,:,0] - (-1)**self.negative_ls*y_lmms[:,:,0].conj()).conj()
        # Shapes of K are (num_sources, num_modes) where num_modes includes only the positive modes (we are doing the reflection trick for negative modes for non-precessing binaries)
        

        # total_fresnel_waveforms_h_plus = jnp.einsum('ni,ijk->jk',K_plus_lms,tf_grid)
        # total_fresnel_waveforms_h_cross = jnp.einsum('ni,ijk->jk',K_cross_lms,tf_grid)

        # h_plus_rotated, h_cross_rotated = imr.rotate_by_polarization_angle(total_fresnel_waveforms_h_plus, total_fresnel_waveforms_h_cross, psi)


        def place_waveform_at_time(waveform_modes, indices_modes,K_plus, K_cross):
            """
            Place waveforms from all modes into the frequency grid for a single time step.
            
            waveform_modes: (n_modes, 2*closest_f_bins) - complex waveform values
            indices_modes: (n_modes, 2*closest_f_bins) - frequency bin indices
            K_plus: (n_modes,) - complex coefficients for plus polarization
            K_cross: (n_modes,) - complex coefficients for cross polarization
            
            Returns: (n_freq,) - summed waveform across modes at correct frequency positions
            """
            # Multiply K coefficients *before* flattening so each mode's scalar
            # broadcasts across its 2*closest_f_bins frequency entries.
            # K_plus/K_cross: (n_modes,), waveform_modes: (n_modes, 2*closest_f_bins) 
            h_plus_modes = K_plus[:, None] * waveform_modes   # (n_modes, 2*closest_f_bins)
            h_cross_modes = K_cross[:, None] * waveform_modes

            # Now flatten across modes and frequency bins
            flat_h_plus = h_plus_modes.flatten()
            flat_h_cross = h_cross_modes.flatten()
            flat_indices = indices_modes.flatten()

            # Mask out-of-bounds indices: zero their contributions
            valid_mask = (flat_indices >= 0) & (flat_indices < n_freq)
            flat_h_plus = jnp.where(valid_mask, flat_h_plus, 0.0)
            flat_h_cross = jnp.where(valid_mask, flat_h_cross, 0.0)
            
            # Clip indices to valid range so .at[].add() doesn't error with out-of-bounds indices.
            # The zeroed values mean nothing is actually added for these entries.
            flat_indices = jnp.clip(flat_indices, 0, n_freq - 1)

            result_plus = jnp.zeros(n_freq, dtype=jnp.complex128).at[flat_indices].add(flat_h_plus)
            result_cross = jnp.zeros(n_freq, dtype=jnp.complex128).at[flat_indices].add(flat_h_cross)

            return result_plus, result_cross

        def process_source(waveforms_per_source, indices_per_source,K_plus, K_cross):
            """
            Process all time steps for a single source.
            
            waveforms_per_source: (n_times, n_modes, 2*closest_f_bins), this is a version of the TF grid for one source (with the wrong frequency axis)
            indices_per_source: (n_times, n_modes, 2*closest_f_bins)
            K_plus: (n_modes,) - complex coefficients for plus polarization
            K_cross: (n_modes,) - complex coefficients for cross polarization
            
            Returns: (n_times, n_freq) - TF map for this source
            """
            # This is vmapping across timesteps
            return jax.vmap(place_waveform_at_time, in_axes = (0, 0, None, None) )(waveforms_per_source, indices_per_source,K_plus, K_cross)

        # NOTE: this is a 2 nested vmap, its just done like this right now for readability and debugging. 
        # Vmap over sources to get final tf_grid with shape (num_sources, num_times, num_freq)
        tf_grid_plus, tf_grid_cross = jax.vmap(process_source)(
            waveform_storage_transposed,
            frequency_indices_transposed,
            K_plus_lms,
            K_cross_lms
        ) # vmap over *SOURCES*

        # Rotate by polarization angle psi for each source (applied to all modes in the same way)
        tf_grid_plus, tf_grid_cross = jax.vmap(self.rotate_by_polarization_angle)(
            tf_grid_plus, tf_grid_cross, wf_params.psi
        )
        
        
        return(tf_grid_plus, tf_grid_cross) #Each (time_grid, frequency_grid, tf_grid) # Returning the full TF grid for all sources.


    @jax.jit(static_argnums=[0,16])
    def get_tf_fresnel_waveform_vanilla_TF_midpoint(self,
                                time_grid: Array,
                                frequency_grid: Array,
                                m1: float | Array,
                                m2: float | Array,
                                chi1z: float | Array,
                                chi2z: float | Array,
                                distance: float | Array,
                                phi_ref: float | Array,
                                f_ref: float | Array,
                                f_min: float | Array,
                                inclination: float | Array,
                                psi: float | Array,
                                delta_t: float = 15.0,
                                t_min: float = jnp.nan,
                                t_ref: float = jnp.nan,
                                closest_f_bins: int = 10,
                                time_of_projections : float | Array = 0.0,
                            ) -> tuple[Array, Array, Array, Array]: # Check dimensionality of this when done. 

        """
        Implementation of time-frequency Fresnel waveform generation.

        Everything aligning at merger. 
        """

        num_sources = jnp.atleast_1d(m1).shape[0]

        # print("Number of sources: ", num_sources)
        # Ignore times for now 
        wf_params, amplitude_coeffs_22, phase_coeffs_22 = (
                    self.initial_processing_TF(
                        m1,
                        m2,
                        chi1z,
                        chi2z,
                        distance,
                        phi_ref,
                        f_ref,
                        f_min,
                        inclination,
                        psi,
                        delta_t,
                        t_min,
                        t_ref,
                    )
                )
            
        # This is the minimum time for every waveform in the batch in mass units 
        min_time_M_units = wf_params.Mt_min 
        # print('min time M units:',min_time_M_units)

        #Convert every single min time to physical units (seconds) to see what is the longest waveform in absolute (real) time
        time_min_physical_all = mass_to_second(min_time_M_units, wf_params.total_mass)

        # print('All time min physical (s):',time_min_physical_all)

        # Pad to smallest min time (real units) to ensure all waveforms fit in the time grid
        min_time_s_units = jnp.min(time_min_physical_all)
        # print('Padded min time (real units):',min_time_s_units)

        # Check the length of the longest signal is not longer than the grid: 
        # assert jnp.abs(min_time_s_units) > jnp.abs(time_grid[-1]), "Time grid is not long enough to contain the longest waveform!"
        # print('Time min physical (s):',min_time_s_units)

        # print('Original time grid:',time_grid)

        # shift time grid to be negative, limited by the length of the longest waveform. (Physical units, seconds)
        time_grid += min_time_s_units
        # print('Shifted time grid (should be negative):',time_grid)
    

        # Work out what OUR time grid corresponds to in mass units for each binary 
        time_grids_mass_units = jax.vmap(second_to_mass, in_axes=(None, 0))(time_grid, wf_params.total_mass)

        new_mask = jnp.ones_like(time_grid, dtype=bool)


        # print('Time grid in mass units:',time_grids_mass_units,time_grids_mass_units.shape)

        # Compute amplitudes and phases for every binary over the time grid and mask    
        # Note: new_mask is the same for all sources, so we use in_axes=None for it (which are in seconds intiially and mapped uniquely to mass units for each binary)
        # amplitudes, phases = jax.vmap(self._compute_all_modes, in_axes = (0, None, 0, 0, 0))(
        #     time_grids_mass_units,
        #     new_mask,
        #     wf_params,
        #     amplitude_coeffs_22,
        #     phase_coeffs_22,
        # )  

        t_grid_midpoints = 0.5 * (time_grid[:-1] + time_grid[1:])  # Midpoints between time grid edges, shape (n_times - 1,)
        t_grid_midpoints_mass_units = jax.vmap(second_to_mass, in_axes=(None, 0))(t_grid_midpoints, wf_params.total_mass)
        midpoint_mask = jnp.ones_like(t_grid_midpoints, dtype=bool)  
        
        # Compute amplitudes and phases at midpoints of each tranche for each binary
        amplitudes, phases = jax.vmap(self._compute_all_modes, in_axes = (0, None, 0, 0, 0))(
            t_grid_midpoints_mass_units,
            midpoint_mask,
            wf_params,
            amplitude_coeffs_22,
            phase_coeffs_22,
        )

        n_modes = amplitudes.shape[1]

       
       # Get higher order modes phase coeffs
        phase_hm_coeffs,_ = jax.vmap(
            lambda wp, pc22: jax.vmap(
                lambda mode: self._compute_phase_coeffs_hm(mode, wp, pc22)
            )(self.higher_modes)
        )(wf_params, phase_coeffs_22)

        # print('Phase HM coeffs:',phase_hm_coeffs)

        # Combine 22 and HM phase coeffs 
        overall_phase_coeffs = jax.tree_util.tree_map(
            lambda p22, phm: jnp.concatenate([p22[:, None], phm], axis=1),
            phase_coeffs_22,
            phase_hm_coeffs,
        )
        # print('Phase overall coeffs:',overall_phase_coeffs)

        # amplitudes shape: [num_sources, num_modes, num_times]
        # amp_factor shape: [num_sources] -> need to reshape for broadcasting
        amplitudes *= wf_params.amp_factor[:, None, None]

        # # For each source find the time at which to begin the waveform. (Is this handled inside the waveform parameter computation? i have no idea)
        # t_min_index = jnp.nonzero(jnp.abs(amplitudes[:,0,:]),axis=1)

        # Back to sensible and positive time grid
        time_grid -= min_time_s_units
        t_grid_midpoints = 0.5 * (time_grid[:-1] + time_grid[1:])
        
        # Frequency grid spacing (assumed uniform)
        dF = frequency_grid[1] - frequency_grid[0]

        # Build per-step inputs and scan over time tranches to keep the loop JAX-native.
        t0_all = time_grid[:-1] # Beginning times for all the tranches (Physical units, seconds)
        t1_all = time_grid[1:] # Ending times for all the tranches (Physical units, seconds)
        tmid_all = t_grid_midpoints # Midpoint times for all the tranches (Physical units, seconds)


        # Convert midpoints to mass units for computations of f,fdot 
        tmid_mass_all = jax.vmap(
            lambda t_mid: jax.vmap(second_to_mass, in_axes=(None, 0))(
                t_mid + min_time_s_units, wf_params.total_mass # Need the shift here in t_mid as remember t_mid in seconds starts at 0 
            )
        )(tmid_all)

        # Transpose amplitudes and phases to shape (num_times, num_sources, num_modes) for scanning over time tranches.
        amps_all = amplitudes.transpose(2, 0, 1)    
        phases_all = phases.transpose(2, 0, 1)

        # Precompute frequency-evolution quantities shared by each time tranche.
        f_0_all = (
            jax.vmap(
                lambda t_mid_mass: jax.vmap(
                    lambda t, eta, pc: jax.vmap(lambda p: imr_omega(t, eta, p))(pc)
                )(t_mid_mass, wf_params.eta, overall_phase_coeffs)
            )(tmid_mass_all)
            / (2 * jnp.pi)
        )# IN MASS UNITS

        # Precompute f_dot at midpoints for all sources and modes.
        f_dot_all = (
            jax.vmap(
                lambda t_mid_mass: jax.vmap(
                    lambda t, eta, pc: jax.vmap(lambda p: imr_omega_dot(t, eta, p))(pc)
                )(t_mid_mass, wf_params.eta, overall_phase_coeffs)
            )(tmid_mass_all)
            / (2 * jnp.pi)
        )# IN MASS UNITS

        f_0_all = jax.vmap(
            lambda f0_t: jax.vmap(mass_to_hz, in_axes=(0, 0))(f0_t, wf_params.total_mass)
        )(f_0_all)# Convert f_0 to Hz

        f_dot_all = jax.vmap(
            lambda fd_t: jax.vmap(df_dt_to_Hz_squared, in_axes=(0, 0))(
                fd_t, wf_params.total_mass
            )
        )(f_dot_all)# Convert f_dot to Hz^2
        
        # Work out for each source, for each mode, for each time segment, what are the closest frequencies on the grid.
        closest_frequency_indexes_all = jnp.round(
            (f_0_all - frequency_grid[0]) / dF
        ).astype(jnp.int32)

        # Clip to valid range to avoid out-of-bounds indexing later (we will mask out contributions from out-of-bounds frequencies anyway, so the clipping won't affect the final result)
        closest_frequency_indexes_all = jnp.clip(
            closest_frequency_indexes_all, 0, frequency_grid.size - 1
        )

        # Get the actual closest frequencies from the grid for each source, mode, and time segment.
        closest_frequencies_all = frequency_grid[closest_frequency_indexes_all]

        # For every frequency in closest_frequencies_all, we will generate a frequency array around it +/- closest_f_bins by going in steps of dF inside the scan loop.
        freq_offsets = jnp.arange(0, 2 * closest_f_bins, dtype=frequency_grid.dtype)
        idx_offsets = jnp.arange(0, 2 * closest_f_bins, dtype=jnp.int32)
        
        # Compute the frequency arrays and corresponding indices for all sources, modes, and time segments at once.
        frequencies_all = (
            closest_frequencies_all[:, :, :, None]
            + (freq_offsets[None, None, None, :] - closest_f_bins) * dF
        )
        frequency_indices_all = (
            closest_frequency_indexes_all[:, :, :, None]
            + (idx_offsets[None, None, None, :] - closest_f_bins)
        )

        def scan_step(_, scan_inputs):
            t_0, t_1, t_midpoint, Amps, Phases, f_0, f_dot, frequencies, frequency_indices = scan_inputs

            h_prefactor = (
                Amps[:, :, jnp.newaxis]
                * jnp.exp(1j * Phases[:, :, jnp.newaxis])
                / jnp.sqrt(2 * f_dot[:, :, jnp.newaxis])
                * jnp.exp(-2 * 1j * jnp.pi * frequencies * (t_midpoint - t_0))
                * jnp.exp(
                    -1j
                    * jnp.pi
                    * ((f_0[:, :, jnp.newaxis] - frequencies) ** 2)
                    / f_dot[:, :, jnp.newaxis]
                )
            )

            v_nm_end = v(f_dot, t_midpoint, t_1, frequencies, f_0)
            v_nm_begin = v(f_dot, t_midpoint, t_0, frequencies, f_0)
            S_vn_end, C_vn_end = jax.scipy.special.fresnel(v_nm_end)
            S_vn_begin, C_vn_begin = jax.scipy.special.fresnel(v_nm_begin)

            I = C_vn_end - C_vn_begin + 1j * (S_vn_end - S_vn_begin)
            waveform = h_prefactor * I

            return None, (waveform, frequency_indices)

        _, (waveform_steps, frequency_indices_steps) = jax.lax.scan(
            scan_step,
            None,
            (
                t0_all,
                t1_all,
                tmid_all,
                amps_all,
                phases_all,
                f_0_all,
                f_dot_all,
                frequencies_all,
                frequency_indices_all,
            ),
        )

        waveform_storage = waveform_steps
        frequency_indices_storage = frequency_indices_steps

        # Note in theory one can do the direct likelihood/inner product computation directly from waveform storage I think. 
        # TEMPORARY/DEV
        # Transpose to (num_sources, num_times, num_modes, 2*closest_f_bins) for vmapping (basically changing around order of axes)
        waveform_storage_transposed = waveform_storage.transpose(1, 0, 2, 3)
        frequency_indices_transposed = frequency_indices_storage.transpose(1, 0, 2, 3)

        # Number of frequency bins in the full grid
        n_freq = frequency_grid.size # TODO: can be precomputed before this function. 

        # Generate spherical harmonics for all modes and sources at once.
        y_lms = spin_weighted_spherical_harmonic_all_modes(
                    jnp.atleast_1d(inclination)[:, None],
                    jnp.pi / 2.0 - jnp.atleast_1d(phi_ref)[:, None],
                    self.ells,
                    self.mms,
                ) #Shape (num_sources, num_modes,1)
        
        y_lmms = spin_weighted_spherical_harmonic_all_modes(
            jnp.atleast_1d(inclination)[:, None],
            jnp.pi / 2.0 - jnp.atleast_1d(phi_ref)[:, None],
            self.negative_ls,
            self.negative_mms, 
            ) #Shape (num_sources, num_modes,1)
        
        K_plus_lms = 1/2*(y_lms[:,:,0] + (-1)**self.negative_ls*y_lmms[:,:,0].conj()).conj() # Overall Conj to flip the fourier convention (Compared to that of Marsat appendix. )
        K_cross_lms = 1j/2*(y_lms[:,:,0] - (-1)**self.negative_ls*y_lmms[:,:,0].conj()).conj()
        # Shapes of K are (num_sources, num_modes) where num_modes includes only the positive modes (we are doing the reflection trick for negative modes for non-precessing binaries)
        

        # total_fresnel_waveforms_h_plus = jnp.einsum('ni,ijk->jk',K_plus_lms,tf_grid)
        # total_fresnel_waveforms_h_cross = jnp.einsum('ni,ijk->jk',K_cross_lms,tf_grid)

        # h_plus_rotated, h_cross_rotated = imr.rotate_by_polarization_angle(total_fresnel_waveforms_h_plus, total_fresnel_waveforms_h_cross, psi)


        def place_waveform_at_time(waveform_modes, indices_modes,K_plus, K_cross):
            """
            Place waveforms from all modes into the frequency grid for a single time step.
            
            waveform_modes: (n_modes, 2*closest_f_bins) - complex waveform values
            indices_modes: (n_modes, 2*closest_f_bins) - frequency bin indices
            K_plus: (n_modes,) - complex coefficients for plus polarization
            K_cross: (n_modes,) - complex coefficients for cross polarization
            
            Returns: (n_freq,) - summed waveform across modes at correct frequency positions
            """
            # Multiply K coefficients *before* flattening so each mode's scalar
            # broadcasts across its 2*closest_f_bins frequency entries.
            # K_plus/K_cross: (n_modes,), waveform_modes: (n_modes, 2*closest_f_bins) 
            h_plus_modes = K_plus[:, None] * waveform_modes   # (n_modes, 2*closest_f_bins)
            h_cross_modes = K_cross[:, None] * waveform_modes

            # Now flatten across modes and frequency bins
            flat_h_plus = h_plus_modes.flatten()
            flat_h_cross = h_cross_modes.flatten()
            flat_indices = indices_modes.flatten()

            # Mask out-of-bounds indices: zero their contributions
            valid_mask = (flat_indices >= 0) & (flat_indices < n_freq)
            flat_h_plus = jnp.where(valid_mask, flat_h_plus, 0.0)
            flat_h_cross = jnp.where(valid_mask, flat_h_cross, 0.0)
            
            # Clip indices to valid range so .at[].add() doesn't error with out-of-bounds indices.
            # The zeroed values mean nothing is actually added for these entries.
            flat_indices = jnp.clip(flat_indices, 0, n_freq - 1)

            result_plus = jnp.zeros(n_freq, dtype=jnp.complex128).at[flat_indices].add(flat_h_plus)
            result_cross = jnp.zeros(n_freq, dtype=jnp.complex128).at[flat_indices].add(flat_h_cross)

            return result_plus, result_cross

        def process_source(waveforms_per_source, indices_per_source,K_plus, K_cross):
            """
            Process all time steps for a single source.
            
            waveforms_per_source: (n_times, n_modes, 2*closest_f_bins), this is a version of the TF grid for one source (with the wrong frequency axis)
            indices_per_source: (n_times, n_modes, 2*closest_f_bins)
            K_plus: (n_modes,) - complex coefficients for plus polarization
            K_cross: (n_modes,) - complex coefficients for cross polarization
            
            Returns: (n_times, n_freq) - TF map for this source
            """
            # This is vmapping across timesteps
            return jax.vmap(place_waveform_at_time, in_axes = (0, 0, None, None) )(waveforms_per_source, indices_per_source,K_plus, K_cross)

        # NOTE: this is a 2 nested vmap, its just done like this right now for readability and debugging. 
        # Vmap over sources to get final tf_grid with shape (num_sources, num_times, num_freq)
        tf_grid_plus, tf_grid_cross = jax.vmap(process_source)(
            waveform_storage_transposed,
            frequency_indices_transposed,
            K_plus_lms,
            K_cross_lms
        ) # vmap over *SOURCES*

        # Rotate by polarization angle psi for each source (applied to all modes in the same way)
        tf_grid_plus, tf_grid_cross = jax.vmap(self.rotate_by_polarization_angle)(
            tf_grid_plus, tf_grid_cross, wf_params.psi
        )
        
        
        return(tf_grid_plus, tf_grid_cross) #Each (time_grid, frequency_grid, tf_grid) # Returning the full TF grid for all sources.



@jax.jit
def v(f_dot_0,t_0,t_1,f,f_0):
    fresnel_argument = jnp.sqrt(2*f_dot_0[:,:,jnp.newaxis])*((t_1-t_0) + (f_0[:,:,jnp.newaxis]-f)/f_dot_0[:,:,jnp.newaxis])
    return fresnel_argument
